#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kdiff3
Version  : 17e52c0d1b257d37f5fa42908d67d7019f9476f8
Release  : 3
URL      : https://github.com/KDE/kdiff3/archive/17e52c0d1b257d37f5fa42908d67d7019f9476f8.tar.gz
Source0  : https://github.com/KDE/kdiff3/archive/17e52c0d1b257d37f5fa42908d67d7019f9476f8.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: kdiff3-bin = %{version}-%{release}
Requires: kdiff3-data = %{version}-%{release}
Requires: kdiff3-lib = %{version}-%{release}
Requires: kdiff3-license = %{version}-%{release}
Requires: kdiff3-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data

%description
KDiff3-Readme
=============
Author: Joachim Eibl  (joachim.eibl at gmx.de)
Port to KF5/Qt5 by Michael Reeves (reeves.87@gmail.com)
KDiff3-Version: 1.7.90

%package bin
Summary: bin components for the kdiff3 package.
Group: Binaries
Requires: kdiff3-data = %{version}-%{release}
Requires: kdiff3-license = %{version}-%{release}

%description bin
bin components for the kdiff3 package.


%package data
Summary: data components for the kdiff3 package.
Group: Data

%description data
data components for the kdiff3 package.


%package doc
Summary: doc components for the kdiff3 package.
Group: Documentation
Requires: kdiff3-man = %{version}-%{release}

%description doc
doc components for the kdiff3 package.


%package lib
Summary: lib components for the kdiff3 package.
Group: Libraries
Requires: kdiff3-data = %{version}-%{release}
Requires: kdiff3-license = %{version}-%{release}

%description lib
lib components for the kdiff3 package.


%package license
Summary: license components for the kdiff3 package.
Group: Default

%description license
license components for the kdiff3 package.


%package man
Summary: man components for the kdiff3 package.
Group: Default

%description man
man components for the kdiff3 package.


%prep
%setup -q -n kdiff3-17e52c0d1b257d37f5fa42908d67d7019f9476f8
cd %{_builddir}/kdiff3-17e52c0d1b257d37f5fa42908d67d7019f9476f8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588705345
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1588705345
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdiff3
cp %{_builddir}/kdiff3-17e52c0d1b257d37f5fa42908d67d7019f9476f8/COPYING %{buildroot}/usr/share/package-licenses/kdiff3/47c547529aa3a83793060dc46dd05d2eb284de83
cp %{_builddir}/kdiff3-17e52c0d1b257d37f5fa42908d67d7019f9476f8/diff_ext_for_kdiff3/LICENSE %{buildroot}/usr/share/package-licenses/kdiff3/6c284580296aa36e06810ccb61e130fc422eb4d4
cp %{_builddir}/kdiff3-17e52c0d1b257d37f5fa42908d67d7019f9476f8/windows_installer/COPYING.txt %{buildroot}/usr/share/package-licenses/kdiff3/25f89a2de584606893a813a5a457400d4755a5ef
cp %{_builddir}/kdiff3-17e52c0d1b257d37f5fa42908d67d7019f9476f8/windows_installer/DIFF-EXT-LICENSE.txt %{buildroot}/usr/share/package-licenses/kdiff3/6c284580296aa36e06810ccb61e130fc422eb4d4
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kdiff3

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kdiff3.desktop
/usr/share/icons/hicolor/128x128/apps/kdiff3.png
/usr/share/icons/hicolor/16x16/apps/kdiff3.png
/usr/share/icons/hicolor/22x22/apps/kdiff3.png
/usr/share/icons/hicolor/256x256/apps/kdiff3.png
/usr/share/icons/hicolor/32x32/apps/kdiff3.png
/usr/share/icons/hicolor/48x48/apps/kdiff3.png
/usr/share/icons/hicolor/64x64/apps/kdiff3.png
/usr/share/icons/hicolor/scalable/apps/kdiff3.svgz
/usr/share/kservices5/kdiff3part.desktop
/usr/share/kxmlgui5/kdiff3/kdiff3_shell.rc
/usr/share/kxmlgui5/kdiff3part/kdiff3_part.rc
/usr/share/metainfo/org.kde.kdiff3.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/en/kdiff3/dirbrowser.png
/usr/share/doc/HTML/en/kdiff3/dirmergebig.png
/usr/share/doc/HTML/en/kdiff3/index.cache.bz2
/usr/share/doc/HTML/en/kdiff3/index.docbook
/usr/share/doc/HTML/en/kdiff3/iteminfo.png
/usr/share/doc/HTML/en/kdiff3/letter_by_letter.png
/usr/share/doc/HTML/en/kdiff3/merge_current.png
/usr/share/doc/HTML/en/kdiff3/new.png
/usr/share/doc/HTML/en/kdiff3/open_dialog.png
/usr/share/doc/HTML/en/kdiff3/screenshot_diff.png
/usr/share/doc/HTML/en/kdiff3/screenshot_merge.png
/usr/share/doc/HTML/en/kdiff3/triple_diff.png
/usr/share/doc/HTML/en/kdiff3/white_space.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kf5/kfileitemaction/kdiff3fileitemaction.so
/usr/lib64/qt5/plugins/kf5/parts/kdiff3part.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdiff3/25f89a2de584606893a813a5a457400d4755a5ef
/usr/share/package-licenses/kdiff3/47c547529aa3a83793060dc46dd05d2eb284de83
/usr/share/package-licenses/kdiff3/6c284580296aa36e06810ccb61e130fc422eb4d4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/kdiff3.1
