#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF442B36D614B06BC (reeves.87@gmail.com)
#
Name     : kdiff3
Version  : 1.9.3
Release  : 8
URL      : https://download.kde.org/stable/kdiff3/kdiff3-1.9.3.tar.xz
Source0  : https://download.kde.org/stable/kdiff3/kdiff3-1.9.3.tar.xz
Source1  : https://download.kde.org/stable/kdiff3/kdiff3-1.9.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0 MIT
Requires: kdiff3-bin = %{version}-%{release}
Requires: kdiff3-data = %{version}-%{release}
Requires: kdiff3-lib = %{version}-%{release}
Requires: kdiff3-license = %{version}-%{release}
Requires: kdiff3-locales = %{version}-%{release}
Requires: kdiff3-man = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data

%description
KDiff3-Readme
=============
Author: Joachim Eibl  (joachim.eibl at gmx.de)
Port to KF5/Qt5 by Michael Reeves (reeves.87@gmail.com)
KDiff3-Version: 1.9.3

%package bin
Summary: bin components for the kdiff3 package.
Group: Binaries
Requires: kdiff3-data = %{version}-%{release}
Requires: kdiff3-license = %{version}-%{release}

%description bin
bin components for the kdiff3 package.


%package data
Summary: data components for the kdiff3 package.
Group: Data

%description data
data components for the kdiff3 package.


%package doc
Summary: doc components for the kdiff3 package.
Group: Documentation
Requires: kdiff3-man = %{version}-%{release}

%description doc
doc components for the kdiff3 package.


%package lib
Summary: lib components for the kdiff3 package.
Group: Libraries
Requires: kdiff3-data = %{version}-%{release}
Requires: kdiff3-license = %{version}-%{release}

%description lib
lib components for the kdiff3 package.


%package license
Summary: license components for the kdiff3 package.
Group: Default

%description license
license components for the kdiff3 package.


%package locales
Summary: locales components for the kdiff3 package.
Group: Default

%description locales
locales components for the kdiff3 package.


%package man
Summary: man components for the kdiff3 package.
Group: Default

%description man
man components for the kdiff3 package.


%prep
%setup -q -n kdiff3-1.9.3
cd %{_builddir}/kdiff3-1.9.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631079485
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1631079485
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdiff3
cp %{_builddir}/kdiff3-1.9.3/COPYING %{buildroot}/usr/share/package-licenses/kdiff3/47c547529aa3a83793060dc46dd05d2eb284de83
cp %{_builddir}/kdiff3-1.9.3/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/kdiff3/680ed9349d3d12bd39ddd36e8c4bc6b1b0cb1c0e
cp %{_builddir}/kdiff3-1.9.3/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kdiff3/e712eadfab0d2357c0f50f599ef35ee0d87534cb
cp %{_builddir}/kdiff3-1.9.3/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/kdiff3/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
cp %{_builddir}/kdiff3-1.9.3/diff_ext_for_kdiff3/LICENSE %{buildroot}/usr/share/package-licenses/kdiff3/6c284580296aa36e06810ccb61e130fc422eb4d4
cp %{_builddir}/kdiff3-1.9.3/windows_installer/COPYING.txt %{buildroot}/usr/share/package-licenses/kdiff3/25f89a2de584606893a813a5a457400d4755a5ef
cp %{_builddir}/kdiff3-1.9.3/windows_installer/DIFF-EXT-LICENSE.txt %{buildroot}/usr/share/package-licenses/kdiff3/6c284580296aa36e06810ccb61e130fc422eb4d4
pushd clr-build
%make_install
popd
%find_lang kdiff3
%find_lang kdiff3fileitemactionplugin
%find_lang diff_ext

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kdiff3

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kdiff3.desktop
/usr/share/icons/hicolor/128x128/apps/kdiff3.png
/usr/share/icons/hicolor/16x16/apps/kdiff3.png
/usr/share/icons/hicolor/22x22/apps/kdiff3.png
/usr/share/icons/hicolor/256x256/apps/kdiff3.png
/usr/share/icons/hicolor/32x32/apps/kdiff3.png
/usr/share/icons/hicolor/48x48/apps/kdiff3.png
/usr/share/icons/hicolor/64x64/apps/kdiff3.png
/usr/share/icons/hicolor/scalable/apps/kdiff3.svgz
/usr/share/kxmlgui5/kdiff3/kdiff3_shell.rc
/usr/share/kxmlgui5/kdiff3part/kdiff3_part.rc
/usr/share/metainfo/org.kde.kdiff3.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kdiff3/index.cache.bz2
/usr/share/doc/HTML/ca/kdiff3/index.docbook
/usr/share/doc/HTML/ca/kdiff3/open_dialog.png
/usr/share/doc/HTML/de/kdiff3/index.cache.bz2
/usr/share/doc/HTML/de/kdiff3/index.docbook
/usr/share/doc/HTML/en/kdiff3/dirbrowser.png
/usr/share/doc/HTML/en/kdiff3/dirmergebig.png
/usr/share/doc/HTML/en/kdiff3/index.cache.bz2
/usr/share/doc/HTML/en/kdiff3/index.docbook
/usr/share/doc/HTML/en/kdiff3/iteminfo.png
/usr/share/doc/HTML/en/kdiff3/letter_by_letter.png
/usr/share/doc/HTML/en/kdiff3/merge_current.png
/usr/share/doc/HTML/en/kdiff3/new.png
/usr/share/doc/HTML/en/kdiff3/open_dialog.png
/usr/share/doc/HTML/en/kdiff3/screenshot_diff.png
/usr/share/doc/HTML/en/kdiff3/screenshot_merge.png
/usr/share/doc/HTML/en/kdiff3/triple_diff.png
/usr/share/doc/HTML/en/kdiff3/white_space.png
/usr/share/doc/HTML/es/kdiff3/index.cache.bz2
/usr/share/doc/HTML/es/kdiff3/index.docbook
/usr/share/doc/HTML/it/kdiff3/index.cache.bz2
/usr/share/doc/HTML/it/kdiff3/index.docbook
/usr/share/doc/HTML/nl/kdiff3/index.cache.bz2
/usr/share/doc/HTML/nl/kdiff3/index.docbook
/usr/share/doc/HTML/sv/kdiff3/index.cache.bz2
/usr/share/doc/HTML/sv/kdiff3/index.docbook
/usr/share/doc/HTML/uk/kdiff3/index.cache.bz2
/usr/share/doc/HTML/uk/kdiff3/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kf5/kfileitemaction/kdiff3fileitemaction.so
/usr/lib64/qt5/plugins/kf5/parts/kdiff3part.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdiff3/25f89a2de584606893a813a5a457400d4755a5ef
/usr/share/package-licenses/kdiff3/47c547529aa3a83793060dc46dd05d2eb284de83
/usr/share/package-licenses/kdiff3/680ed9349d3d12bd39ddd36e8c4bc6b1b0cb1c0e
/usr/share/package-licenses/kdiff3/6c284580296aa36e06810ccb61e130fc422eb4d4
/usr/share/package-licenses/kdiff3/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
/usr/share/package-licenses/kdiff3/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files man
%defattr(0644,root,root,0755)
/usr/share/man/ca/man1/kdiff3.1
/usr/share/man/de/man1/kdiff3.1
/usr/share/man/es/man1/kdiff3.1
/usr/share/man/it/man1/kdiff3.1
/usr/share/man/man1/kdiff3.1
/usr/share/man/nl/man1/kdiff3.1
/usr/share/man/sv/man1/kdiff3.1
/usr/share/man/uk/man1/kdiff3.1

%files locales -f kdiff3.lang -f kdiff3fileitemactionplugin.lang -f diff_ext.lang
%defattr(-,root,root,-)

